name: My Workflow
on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: RUN 
        run : echo "testing"
      - name: RUN1
        run : echo "testing main 2"  
