name: My Workflow
on: 
  pull_request:
    branches:
      - main
      - 'releases_*'
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: RUN 
        run : echo "testing main"      

